### ISSUE TITLE
숫자 표현 알고리즘 제작

### ISSUE THREAD

**Issue by updaun** [jl749/manual-alphabet_writer_GUI#1]
# What?
- 정적 숫자 표현
- 동적 숫자 표현
-
# Why?
- 지숫자 표현 ( 0 ~ 20 )
- 지화를 화용한 주소 입력 중 숫자 표현 기능

# Todo
- [x] : 정적 숫자 알고리즘 마이그레이션
- [x] : 동적 숫자 알고리즘 마이그레이션
- [x] : 프론트엔드에서 지숫자 계산, 결과값 백엔드로 전송
