### ISSUE TITLE
문자 번역 알고리즘 변환

### ISSUE THREAD

**Issue by updaun** [jl749/manual-alphabet_writer_GUI#4]
# What?
- 지문자 번역 변환

# Why?
- 지문자 표현
- 쌍자음 표현

# Todo
- [ ] 문자 번역 모델 로드
- [ ] 더미 데이터로 모델 가동 상태 확인
- [ ] 랜드마크 정규화
- [ ] 벡터 각도 계산
- [ ] 모델 입력 데이터 제작
- [ ] 쌍자음 표현을 위한 움직임 감지 레퍼런스 변환

**Comment by jl749** [comment]
jsModel 폴더 안에 `point_history_classifier.json` 넣어주세요

**Comment by jl749** [comment]
/**
 * 두 숫자를 더해 값을 리턴합니다
 * a: 더할숫자 1: int
 * b: 더할숫자 2: int
 * return --> 더해진 숫자: int
 */
function add(a, b) {
    return a + b;
}

위에 처럼
파이선에서 옮겨오신 함수들에 무슨 역할을 하는 함수인지 설명을 추가해 주실수 있을까요?

나중에 돌아왔을때도 읽기쉬운 코드였으면 좋겠습니다 :)
